modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Floweynt/tfc-support-indicator/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="tfc"
    mandatory=true
    versionRange="[3.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="jade"
    mandatory=true
    versionRange="[11.0.3,)"
    ordering="NONE"
    side="BOTH"
